name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    env:
      RAILS_ENV: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Set up Rails
      run: |
        bin/setup
        bin/rails tailwindcss:build
    - run: bin/rails test
