name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    env:
      RAILS_ENV: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Cache File associated Tests map
      uses: actions/cache@v3
      with:
        path: file-to-associated-tests-map.json
        key: ftatm-${{ github.sha }}
    - name: Set up Rails
      run: |
        bin/setup
        bin/rails tailwindcss:build
    - run: bundle exec rspec
    - name: Save file-to-associated-test-map
      run: |
        mv {log/,}file-to-associated-tests-map.json
