name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node_index: [0, 1]
    runs-on: ubuntu-latest
    name: Test
    env:
      RAILS_ENV: test
      NODE_NUMBER: 2
      NODE_INDEX: ${{ matrix.node_index }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Set up Rails
      run: |
        bin/setup
        bin/rails tailwindcss:build
        git rev-parse HEAD > REVISION
    - name: Test(parallel)
      run: |
        test_files=$(bin/take-test-groups $NODE_NUMBER $NODE_INDEX)

        bundle exec rspec $test_files
    - uses: actions/upload-artifact@v3
      with:
        name: affected-tests-map-${{ matrix.node_index }}
        path: log/affected-tests-map.json
  merge_map:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Cache File associated Tests map
      uses: actions/cache@v3
      with:
        path: affected-tests-map.json
        key: map-v3-${{ github.sha }}
    - uses: actions/download-artifact@v3
      with:
        path: .
    - name: Merge affected-tests-map
      run: |
        bundle exec bin/merge-tests-map 2
